# Spark DataFrame Basic Operations

In [1]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Spark DataFrame Basic Operations").getOrCreate()

In [2]:
df=spark.read.csv('C:/Users/User/Desktop/Data/appl_stock.csv',inferSchema=True, header=True)

In [18]:
df.show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [19]:
df.describe().show()

+-------+----------+------------------+------------------+------------------+-----------------+-------------------+------------------+
|summary|      Date|              Open|              High|               Low|            Close|             Volume|         Adj Close|
+-------+----------+------------------+------------------+------------------+-----------------+-------------------+------------------+
|  count|      1762|              1762|              1762|              1762|             1762|               1762|              1762|
|   mean|      null| 313.0763111589103| 315.9112880164581| 309.8282405079457|312.9270656379113|9.422577587968218E7| 75.00174115607275|
| stddev|      null|185.29946803981522|186.89817686485767|183.38391664371008|185.1471036170943|6.020518776592709E7| 28.57492972179906|
|    min|2010-01-04|              90.0|         90.699997|         89.470001|        90.279999|           11475900|         24.881912|
|    max|2016-12-30|        702.409988|        705.070023|        699.569977|       702.100021|          470249500|127.96609099999999|
+-------+----------+------------------+------------------+------------------+-----------------+-------------------+------------------+

In [32]:
df.printSchema()

root
 |-- Date: string (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [25]:
df.select('High').show()

+------------------+
|              High|
+------------------+
|        214.499996|
|        215.589994|
|            215.23|
|        212.000006|
|        212.000006|
|        213.000002|
|209.76999500000002|
|210.92999500000002|
|210.45999700000002|
|211.59999700000003|
|215.18999900000003|
|        215.549994|
|213.30999599999998|
|        207.499996|
|        204.699999|
|        213.710005|
|            210.58|
|        205.500004|
|        202.199995|
|             196.0|
+------------------+
only showing top 20 rows

In [33]:
df.head(2)[0]

Row(Date='2010-01-04', Open=213.429998, High=214.499996, Low=212.38000099999996, Close=214.009998, Volume=123432400, Adj Close=27.727039)

# Pass SQL Queries Syntax without Creating View

In [35]:
df.filter("Close < 500").show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [37]:
df.filter('Close < 500').select (["Date","Open","Volume"]).show()

+----------+------------------+---------+
|      Date|              Open|   Volume|
+----------+------------------+---------+
|2010-01-04|        213.429998|123432400|
|2010-01-05|        214.599998|150476200|
|2010-01-06|        214.379993|138040000|
|2010-01-07|            211.75|119282800|
|2010-01-08|        210.299994|111902700|
|2010-01-11|212.79999700000002|115557400|
|2010-01-12|209.18999499999998|148614900|
|2010-01-13|        207.870005|151473000|
|2010-01-14|210.11000299999998|108223500|
|2010-01-15|210.92999500000002|148516900|
|2010-01-19|        208.330002|182501900|
|2010-01-20|        214.910006|153038200|
|2010-01-21|        212.079994|152038600|
|2010-01-22|206.78000600000001|220441900|
|2010-01-25|202.51000200000001|266424900|
|2010-01-26|205.95000100000001|466777500|
|2010-01-27|        206.849995|430642100|
|2010-01-28|        204.930004|293375600|
|2010-01-29|        201.079996|311488100|
|2010-02-01|192.36999699999998|187469100|
+----------+------------------+---------+
only showing top 20 rows

In [41]:
from databricks import koalas as pd

In [47]:
a=df.filter('Close < 500').select (["Date","Open","Volume","Close"])

In [48]:
a.show()

+----------+------------------+---------+------------------+
|      Date|              Open|   Volume|             Close|
+----------+------------------+---------+------------------+
|2010-01-04|        213.429998|123432400|        214.009998|
|2010-01-05|        214.599998|150476200|        214.379993|
|2010-01-06|        214.379993|138040000|        210.969995|
|2010-01-07|            211.75|119282800|            210.58|
|2010-01-08|        210.299994|111902700|211.98000499999998|
|2010-01-11|212.79999700000002|115557400|210.11000299999998|
|2010-01-12|209.18999499999998|148614900|        207.720001|
|2010-01-13|        207.870005|151473000|        210.650002|
|2010-01-14|210.11000299999998|108223500|            209.43|
|2010-01-15|210.92999500000002|148516900|            205.93|
|2010-01-19|        208.330002|182501900|        215.039995|
|2010-01-20|        214.910006|153038200|            211.73|
|2010-01-21|        212.079994|152038600|        208.069996|
|2010-01-22|206.78000600000001|220441900|            197.75|
|2010-01-25|202.51000200000001|266424900|        203.070002|
|2010-01-26|205.95000100000001|466777500|        205.940001|
|2010-01-27|        206.849995|430642100|        207.880005|
|2010-01-28|        204.930004|293375600|        199.289995|
|2010-01-29|        201.079996|311488100|        192.060003|
|2010-02-01|192.36999699999998|187469100|        194.729998|
+----------+------------------+---------+------------------+
only showing top 20 rows

# Create a Temporal View

In [49]:
df.createOrReplaceTempView("stocks")

In [57]:
results=spark.sql("Select date,open,volume,close from stocks where  close < 500 ").show()

+----------+------------------+---------+------------------+
|      date|              open|   volume|             close|
+----------+------------------+---------+------------------+
|2010-01-04|        213.429998|123432400|        214.009998|
|2010-01-05|        214.599998|150476200|        214.379993|
|2010-01-06|        214.379993|138040000|        210.969995|
|2010-01-07|            211.75|119282800|            210.58|
|2010-01-08|        210.299994|111902700|211.98000499999998|
|2010-01-11|212.79999700000002|115557400|210.11000299999998|
|2010-01-12|209.18999499999998|148614900|        207.720001|
|2010-01-13|        207.870005|151473000|        210.650002|
|2010-01-14|210.11000299999998|108223500|            209.43|
|2010-01-15|210.92999500000002|148516900|            205.93|
|2010-01-19|        208.330002|182501900|        215.039995|
|2010-01-20|        214.910006|153038200|            211.73|
|2010-01-21|        212.079994|152038600|        208.069996|
|2010-01-22|206.78000600000001|220441900|            197.75|
|2010-01-25|202.51000200000001|266424900|        203.070002|
|2010-01-26|205.95000100000001|466777500|        205.940001|
|2010-01-27|        206.849995|430642100|        207.880005|
|2010-01-28|        204.930004|293375600|        199.289995|
|2010-01-29|        201.079996|311488100|        192.060003|
|2010-02-01|192.36999699999998|187469100|        194.729998|
+----------+------------------+---------+------------------+
only showing top 20 rows

In [60]:
#Another Alternative
df.filter(df["Close"]  < 500).select(['Volume','Low']).show()

+---------+------------------+
|   Volume|               Low|
+---------+------------------+
|123432400|212.38000099999996|
|150476200|        213.249994|
|138040000|        210.750004|
|119282800|        209.050005|
|111902700|209.06000500000002|
|115557400|        208.450005|
|148614900|        206.419998|
|151473000|        204.099998|
|108223500|        209.020004|
|148516900|        205.869999|
|182501900|        207.240004|
|153038200|        209.500002|
|152038600|        207.210003|
|220441900|            197.16|
|266424900|        200.190002|
|466777500|        202.580004|
|430642100|        199.530001|
|293375600|        198.699995|
|311488100|        190.250002|
|187469100|191.29999899999999|
+---------+------------------+
only showing top 20 rows

In [62]:
df.filter((df['Close'] > 200) & (df['Close']   < 500) ). show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-02-12|        198.109995|        201.639996|        195.500002|200.37999299999998|163867200|25.961142000000002|
|2010-02-16|        201.940002|        203.690002|        201.520006|        203.399996|135934400|         26.352412|
|2010-02-17|        204.190001|        204.310003|        200.860004|        202.550003|109099200|         26.242287|
|2010-02-18|        201.629995|        203.889994|        200.920006|        202.929998|105706300|         26.291519|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [67]:
b=df['Close'] > 200
c=df['Close'] < 500
d=df['Close'] > 300

In [68]:
df.filter(b  & c).show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-02-12|        198.109995|        201.639996|        195.500002|200.37999299999998|163867200|25.961142000000002|
|2010-02-16|        201.940002|        203.690002|        201.520006|        203.399996|135934400|         26.352412|
|2010-02-17|        204.190001|        204.310003|        200.860004|        202.550003|109099200|         26.242287|
|2010-02-18|        201.629995|        203.889994|        200.920006|        202.929998|105706300|         26.291519|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [69]:
df.filter(b  &  ~ d).show()   # ~ means not , so in this case it means not greater than 300 from the variable

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-02-12|        198.109995|        201.639996|        195.500002|200.37999299999998|163867200|25.961142000000002|
|2010-02-16|        201.940002|        203.690002|        201.520006|        203.399996|135934400|         26.352412|
|2010-02-17|        204.190001|        204.310003|        200.860004|        202.550003|109099200|         26.242287|
|2010-02-18|        201.629995|        203.889994|        200.920006|        202.929998|105706300|         26.291519|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [75]:
df.filter(df["Low"]== 209.020004).show()

+----------+------------------+------------------+----------+------+---------+---------+
|      Date|              Open|              High|       Low| Close|   Volume|Adj Close|
+----------+------------------+------------------+----------+------+---------+---------+
|2010-01-14|210.11000299999998|210.45999700000002|209.020004|209.43|108223500|27.133657|
+----------+------------------+------------------+----------+------+---------+---------+

In [74]:
df.filter(df["Low"]== 209.020004).select ("Date").show()

+----------+
|      Date|
+----------+
|2010-01-14|
+----------+

# .Collect Method ()
* As you recall .show() prints a dataframe for us but for .collect it stores them in a form of a list

In [78]:
df.filter(df["Low"]== 209.020004).collect()

Row(Date='2010-01-14', Open=210.11000299999998, High=210.45999700000002, Low=209.020004, Close=209.43, Volume=108223500, Adj Close=27.133657)

In [82]:
df.filter(b  &  ~ d).collect()

[Row(Date='2010-01-04', Open=213.429998, High=214.499996, Low=212.38000099999996, Close=214.009998, Volume=123432400, Adj Close=27.727039),
 Row(Date='2010-01-05', Open=214.599998, High=215.589994, Low=213.249994, Close=214.379993, Volume=150476200, Adj Close=27.774976000000002),
 Row(Date='2010-01-06', Open=214.379993, High=215.23, Low=210.750004, Close=210.969995, Volume=138040000, Adj Close=27.333178000000004),
 Row(Date='2010-01-07', Open=211.75, High=212.000006, Low=209.050005, Close=210.58, Volume=119282800, Adj Close=27.28265),
 Row(Date='2010-01-08', Open=210.299994, High=212.000006, Low=209.06000500000002, Close=211.98000499999998, Volume=111902700, Adj Close=27.464034),
 Row(Date='2010-01-11', Open=212.79999700000002, High=213.000002, Low=208.450005, Close=210.11000299999998, Volume=115557400, Adj Close=27.221758),
 Row(Date='2010-01-12', Open=209.18999499999998, High=209.76999500000002, Low=206.419998, Close=207.720001, Volume=148614900, Adj Close=26.91211),
 Row(Date='2010-01-13', Open=207.870005, High=210.92999500000002, Low=204.099998, Close=210.650002, Volume=151473000, Adj Close=27.29172),
 Row(Date='2010-01-14', Open=210.11000299999998, High=210.45999700000002, Low=209.020004, Close=209.43, Volume=108223500, Adj Close=27.133657),
 Row(Date='2010-01-15', Open=210.92999500000002, High=211.59999700000003, Low=205.869999, Close=205.93, Volume=148516900, Adj Close=26.680197999999997),
 Row(Date='2010-01-19', Open=208.330002, High=215.18999900000003, Low=207.240004, Close=215.039995, Volume=182501900, Adj Close=27.860484999999997),
 Row(Date='2010-01-20', Open=214.910006, High=215.549994, Low=209.500002, Close=211.73, Volume=153038200, Adj Close=27.431644),
 Row(Date='2010-01-21', Open=212.079994, High=213.30999599999998, Low=207.210003, Close=208.069996, Volume=152038600, Adj Close=26.957455),
 Row(Date='2010-01-25', Open=202.51000200000001, High=204.699999, Low=200.190002, Close=203.070002, Volume=266424900, Adj Close=26.309658000000002),
 Row(Date='2010-01-26', Open=205.95000100000001, High=213.710005, Low=202.580004, Close=205.940001, Volume=466777500, Adj Close=26.681494),
 Row(Date='2010-01-27', Open=206.849995, High=210.58, Low=199.530001, Close=207.880005, Volume=430642100, Adj Close=26.932840000000002),
 Row(Date='2010-02-12', Open=198.109995, High=201.639996, Low=195.500002, Close=200.37999299999998, Volume=163867200, Adj Close=25.961142000000002),
 Row(Date='2010-02-16', Open=201.940002, High=203.690002, Low=201.520006, Close=203.399996, Volume=135934400, Adj Close=26.352412),
 Row(Date='2010-02-17', Open=204.190001, High=204.310003, Low=200.860004, Close=202.550003, Volume=109099200, Adj Close=26.242287),
 Row(Date='2010-02-18', Open=201.629995, High=203.889994, Low=200.920006, Close=202.929998, Volume=105706300, Adj Close=26.291519),
 Row(Date='2010-02-19', Open=201.860001, High=203.200005, Low=201.109997, Close=201.669996, Volume=103867400, Adj Close=26.128273999999998),
 Row(Date='2010-02-22', Open=202.339998, High=202.500002, Low=199.190006, Close=200.419994, Volume=97640900, Adj Close=25.966324),
 Row(Date='2010-02-24', Open=198.229998, High=201.44000400000002, Low=197.840002, Close=200.66, Volume=115141600, Adj Close=25.997419),
 Row(Date='2010-02-25', Open=197.380005, High=202.859997, Low=196.889994, Close=202.000004, Volume=166281500, Adj Close=26.17103),
 Row(Date='2010-02-26', Open=202.379999, High=205.169996, Low=202.000004, Close=204.61999699999998, Volume=126865200, Adj Close=26.510475),
 Row(Date='2010-03-01', Open=205.749996, High=209.500002, Low=205.450003, Close=208.990004, Volume=137523400, Adj Close=27.076651000000002),
 Row(Date='2010-03-02', Open=209.929998, High=210.830006, Low=207.740002, Close=208.85, Volume=141636600, Adj Close=27.058512),
 Row(Date='2010-03-03', Open=208.940002, High=209.869997, Low=207.940006, Close=209.329998, Volume=93013200, Adj Close=27.120701),
 Row(Date='2010-03-04', Open=209.279997, High=210.919994, Low=208.629995, Close=210.71000299999997, Volume=91510300, Adj Close=27.299493),
 Row(Date='2010-03-05', Open=214.940006, High=219.69999500000003, Low=214.62999900000003, Close=218.95000499999998, Volume=224905100, Adj Close=28.367064000000003),
 Row(Date='2010-03-08', Open=220.01000200000001, High=220.090004, Low=218.250002, Close=219.079994, Volume=107472400, Adj Close=28.383906),
 Row(Date='2010-03-09', Open=218.31000299999997, High=224.999996, Low=217.889994, Close=223.020004, Volume=230064800, Adj Close=28.894371999999997),
 Row(Date='2010-03-10', Open=223.829996, High=225.48000699999997, Low=223.19999500000003, Close=224.83999300000002, Volume=149054500, Adj Close=29.130167999999998),
 Row(Date='2010-03-11', Open=223.909998, High=225.500008, Low=223.319998, Close=225.500008, Volume=101425100, Adj Close=29.21568),
 Row(Date='2010-03-12', Open=227.37001, High=227.72999199999998, Low=225.75, Close=226.600006, Volume=104080900, Adj Close=29.358195000000002),
 Row(Date='2010-03-15', Open=225.38000499999998, High=225.500008, Low=220.249994, Close=223.83999599999999, Volume=123375700, Adj Close=29.000609000000004),
 Row(Date='2010-03-16', Open=224.180004, High=224.979996, Low=222.510006, Close=224.44999700000002, Volume=111727000, Adj Close=29.079641),
 Row(Date='2010-03-17', Open=224.899994, High=226.44998900000002, Low=223.26999700000002, Close=224.12000299999997, Volume=112739200, Adj Close=29.036887),
 Row(Date='2010-03-18', Open=224.100002, High=224.999996, Low=222.60999500000003, Close=224.650002, Volume=85527400, Adj Close=29.105553000000004),
 Row(Date='2010-03-19', Open=224.79000499999998, High=225.240002, Low=221.23000299999998, Close=222.25, Volume=139861400, Adj Close=28.79461),
 Row(Date='2010-03-22', Open=220.46999900000003, High=225.999992, Low=220.150005, Close=224.750004, Volume=114104900, Adj Close=29.118509999999997),
 Row(Date='2010-03-23', Open=225.640011, High=228.780003, Low=224.100002, Close=228.359993, Volume=150607800, Adj Close=29.586218),
 Row(Date='2010-03-24', Open=227.64000299999998, High=230.200008, Low=227.50998700000002, Close=229.37000299999997, Volume=149445100, Adj Close=29.717075),
 Row(Date='2010-03-25', Open=230.919998, High=230.970013, Low=226.250011, Close=226.649994, Volume=135571100, Adj Close=29.364671),
 Row(Date='2010-03-26', Open=228.949993, High=231.950008, Low=228.55001099999998, Close=230.899998, Volume=160218800, Adj Close=29.9153),
 Row(Date='2010-03-29', Open=232.999992, High=233.86999900000004, Low=231.619987, Close=232.389992, Volume=135186100, Adj Close=30.108342999999998),
 Row(Date='2010-03-30', Open=236.599995, High=237.479988, Low=234.250008, Close=235.84999100000002, Volume=131827500, Adj Close=30.556619),
 Row(Date='2010-03-31', Open=235.490009, High=236.610008, Low=234.459999, Close=235.000011, Volume=107664900, Adj Close=30.446496000000003),
 Row(Date='2010-04-01', Open=237.41, High=238.73000299999998, Low=232.75, Close=235.96999399999999, Volume=150786300, Adj Close=30.572165999999996),
 Row(Date='2010-04-05', Open=234.980011, High=238.509998, Low=234.76999300000003, Close=238.48999799999999, Volume=171126900, Adj Close=30.898657),
 Row(Date='2010-04-06', Open=238.20000499999998, High=240.23999799999999, Low=237.000004, Close=239.540009, Volume=111754300, Adj Close=31.034696000000004),
 Row(Date='2010-04-07', Open=239.54999500000002, High=241.92001000000002, Low=238.659988, Close=240.600006, Volume=157125500, Adj Close=31.172029),
 Row(Date='2010-04-08', Open=240.440002, High=241.540001, Low=238.040001, Close=239.95000499999998, Volume=143247300, Adj Close=31.087815000000003),
 Row(Date='2010-04-09', Open=241.430012, High=241.889996, Low=240.46000299999997, Close=241.789993, Volume=83545700, Adj Close=31.326203000000003),
 Row(Date='2010-04-12', Open=242.19998900000002, High=243.069996, Low=241.809994, Close=242.29000499999998, Volume=83256600, Adj Close=31.390984000000003),
 Row(Date='2010-04-13', Open=241.860008, High=242.80000299999998, Low=241.110004, Close=242.43000800000002, Volume=76552700, Adj Close=31.409122999999997),
 Row(Date='2010-04-14', Open=245.28000600000001, High=245.810005, Low=244.06999199999998, Close=245.690002, Volume=101019100, Adj Close=31.831485999999998),
 Row(Date='2010-04-15', Open=245.77999100000002, High=249.02999900000003, Low=245.509998, Close=248.92001000000002, Volume=94196200, Adj Close=32.249965),
 Row(Date='2010-04-16', Open=248.569988, High=251.140007, Low=244.55000299999998, Close=247.400002, Volume=187636400, Adj Close=32.053033),
 Row(Date='2010-04-19', Open=247.03000600000001, High=247.88999900000002, Low=241.76999300000003, Close=247.07000699999998, Volume=141731100, Adj Close=32.010279),
 Row(Date='2010-04-20', Open=248.540001, High=249.250004, Low=242.960007, Close=244.590004, Volume=184581600, Adj Close=31.688971000000002),
 Row(Date='2010-04-21', Open=258.799995, High=260.249989, Low=255.72999199999998, Close=259.22000499999996, Volume=245597800, Adj Close=33.584427000000005),
 Row(Date='2010-04-22', Open=258.240009, High=266.750004, Low=256.199989, Close=266.46999700000003, Volume=198356200, Adj Close=34.523733),
 Row(Date='2010-04-23', Open=267.990005, High=272.180008, Low=266.999996, Close=270.82999, Volume=199238900, Adj Close=35.088612),
 Row(Date='2010-04-26', Open=271.880001, High=272.459988, Low=268.19001000000003, Close=269.5, Volume=119767200, Adj Close=34.916299),
 Row(Date='2010-04-27', Open=267.269989, High=267.839989, Low=260.520008, Close=262.039989, Volume=177335900, Adj Close=33.949783000000004),
 Row(Date='2010-04-28', Open=263.250004, High=264.000008, Low=256.410007, Close=261.600006, Volume=189600600, Adj Close=33.892779),
 Row(Date='2010-04-29', Open=263.020012, High=270.000011, Low=262.010002, Close=268.64000699999997, Volume=139710200, Adj Close=34.804879),
 Row(Date='2010-04-30', Open=269.310009, High=270.57001099999997, Low=260.999992, Close=261.090008, Volume=135615900, Adj Close=33.826704),
 Row(Date='2010-05-03', Open=263.840004, High=267.87998999999996, Low=262.880009, Close=266.34999500000004, Volume=113585500, Adj Close=34.508186),
 Row(Date='2010-05-04', Open=262.889996, High=263.290005, Low=256.749989, Close=258.679993, Volume=180954900, Adj Close=33.514464000000004),
 Row(Date='2010-05-05', Open=253.03001, High=258.14000699999997, Low=248.72999199999998, Close=255.98999799999999, Volume=220775800, Adj Close=33.165949),
 Row(Date='2010-05-06', Open=253.830002, High=258.249996, Low=199.249994, Close=246.249989, Volume=321465200, Adj Close=31.904038),
 Row(Date='2010-05-07', Open=243.71001099999998, High=246.569996, Low=225.20998799999998, Close=235.860004, Volume=419004600, Adj Close=30.557916),
 Row(Date='2010-05-10', Open=250.25, High=254.649994, Low=248.529987, Close=253.99000499999997, Volume=246076600, Adj Close=32.906831),
 Row(Date='2010-05-11', Open=251.83999599999999, High=259.89000699999997, Low=250.499992, Close=256.51999700000005, Volume=212226700, Adj Close=33.234615999999995),
 Row(Date='2010-05-12', Open=259.240005, High=263.130001, Low=258.699993, Close=262.090004, Volume=163594900, Adj Close=33.956263),
 Row(Date='2010-05-13', Open=263.21999, High=265.000004, Low=256.399994, Close=258.360012, Volume=149928100, Adj Close=33.473007),
 Row(Date='2010-05-14', Open=255.159992, High=256.47999599999997, Low=249.499996, Close=253.819988, Volume=189840700, Adj Close=32.884803999999995),
 Row(Date='2010-05-17', Open=254.700008, High=256.17998900000003, Low=247.70999500000002, Close=254.219997, Volume=190708700, Adj Close=32.936628999999996),
 Row(Date='2010-05-18', Open=256.980007, High=258.550003, Low=250.25998700000002, Close=252.360008, Volume=195669600, Adj Close=32.695648999999996),
 Row(Date='2010-05-19', Open=249.499996, High=252.919994, Low=244.85001, Close=248.33999599999999, Volume=256431700, Adj Close=32.174818),
 Row(Date='2010-05-20', Open=241.88000899999997, High=243.849987, Low=236.209999, Close=237.75999500000003, Volume=320728800, Adj Close=30.804078000000004),
 Row(Date='2010-05-21', Open=232.819988, High=244.499989, Low=231.349995, Close=242.31999199999998, Volume=305972800, Adj Close=31.394869),
 Row(Date='2010-05-24', Open=247.27999900000003, High=250.900002, Low=246.26000200000001, Close=246.75998700000002, Volume=188559700, Adj Close=31.970113),
 Row(Date='2010-05-25', Open=239.34999100000002, High=246.75998700000002, Low=237.16000699999998, Close=245.220005, Volume=262001600, Adj Close=31.770594),
 Row(Date='2010-05-26', Open=250.080009, High=252.12999, Low=243.750011, Close=244.109993, Volume=212663500, Adj Close=31.626781),
 Row(Date='2010-05-27', Open=250.599995, High=253.89000299999998, Low=249.11000099999998, Close=253.34999100000002, Volume=166570600, Adj Close=32.823910999999995),
 Row(Date='2010-05-28', Open=259.389996, High=259.400009, Low=253.34999100000002, Close=256.880005, Volume=203903700, Adj Close=33.281258),
 Row(Date='2010-06-01', Open=259.690002, High=265.939999, Low=258.95999900000004, Close=260.830002, Volume=219118200, Adj Close=33.793018),
 Row(Date='2010-06-02', Open=264.53999300000004, High=264.799999, Low=260.32999, Close=263.949993, Volume=172137000, Adj Close=34.197243),
 Row(Date='2010-06-03', Open=265.180008, High=265.550003, Low=260.409992, Close=263.11998700000004, Volume=162526700, Adj Close=34.089707000000004),
 Row(Date='2010-06-04', Open=258.209995, High=261.900013, Low=254.629993, Close=255.96001099999998, Volume=189576100, Adj Close=33.162064),
 Row(Date='2010-06-07', Open=258.289997, High=259.14999, Low=250.550007, Close=250.940002, Volume=221735500, Adj Close=32.511674),
 Row(Date='2010-06-08', Open=253.240002, High=253.79998799999998, Low=245.650002, Close=249.330006, Volume=250192600, Adj Close=32.303084000000005),
 Row(Date='2010-06-09', Open=251.47000099999997, High=251.899998, Low=242.490009, Close=243.20001200000002, Volume=213657500, Adj Close=31.508884000000002),
 Row(Date='2010-06-10', Open=244.83999599999999, High=250.98000299999998, Low=242.19998900000002, Close=250.510006, Volume=194089000, Adj Close=32.455964),
 Row(Date='2010-06-11', Open=248.23000699999997, High=253.859989, Low=247.369987, Close=253.50999500000003, Volume=136439800, Adj Close=32.844640999999996),
 Row(Date='2010-06-14', Open=255.96001099999998, High=259.14999, Low=254.010006, Close=254.27999900000003, Volume=150740100, Adj Close=32.944402000000004),
 Row(Date='2010-06-15', Open=255.64000299999998, High=259.850006, Low=255.5, Close=259.690002, Volume=146268500, Adj Close=33.64532),
 Row(Date='2010-06-16', Open=261.09999500000004, High=267.75, Low=260.629997, Close=267.249989, Volume=195919500, Adj Close=34.624789),
 Row(Date='2010-06-17', Open=270.59999799999997, High=272.899998, Low=269.5, Close=271.86998700000004, Volume=218213800, Adj Close=35.223354),
 Row(Date='2010-06-18', Open=272.249996, High=274.999992, Low=271.41999100000004, Close=274.07001099999997, Volume=196155400, Adj Close=35.508388000000004),
 Row(Date='2010-06-21', Open=277.68998700000003, High=279.009991, Low=268.72999599999997, Close=270.170002, Volume=194122600, Adj Close=35.003104),
 Row(Date='2010-06-22', Open=272.160007, High=275.97000099999997, Low=271.499992, Close=273.850006, Volume=179315500, Adj Close=35.479884000000006),
 Row(Date='2010-06-23', Open=274.58000899999996, High=274.660011, Low=267.89999, Close=270.969994, Volume=192114300, Adj Close=35.106751),
 Row(Date='2010-06-24', Open=271.000008, High=273.200005, Low=268.09999500000004, Close=268.999989, Volume=178569300, Adj Close=34.851518),
 Row(Date='2010-06-25', Open=270.06001299999997, High=270.27000400000003, Low=265.810009, Close=266.699989, Volume=137485600, Adj Close=34.553531),
 Row(Date='2010-06-28', Open=266.930008, High=269.749992, Low=264.519993, Close=268.299999, Volume=146237000, Adj Close=34.760827),
 Row(Date='2010-06-29', Open=264.12001000000004, High=264.390003, Low=254.299999, Close=256.170002, Volume=283336200, Adj Close=33.18927),
 Row(Date='2010-06-30', Open=256.709988, High=257.96999, Low=250.00999500000003, Close=251.530003, Volume=184863000, Adj Close=32.588114000000004),
 Row(Date='2010-07-01', Open=254.299999, High=254.80001099999998, Low=243.220013, Close=248.48, Volume=255724000, Adj Close=32.192957),
 Row(Date='2010-07-02', Open=250.49000499999997, High=250.929989, Low=243.20001200000002, Close=246.93999100000002, Volume=173460700, Adj Close=31.993434000000004),
 Row(Date='2010-07-06', Open=251.000004, High=252.799992, Low=246.16, Close=248.62999, Volume=153808900, Adj Close=32.21239),
 Row(Date='2010-07-07', Open=250.49000499999997, High=258.770008, Low=249.749989, Close=258.670006, Volume=163639000, Adj Close=33.51317),
 Row(Date='2010-07-08', Open=262.48, High=262.900009, Low=254.88999900000002, Close=258.089993, Volume=184536100, Adj Close=33.438024),
 Row(Date='2010-07-09', Open=256.889992, High=259.899994, Low=255.159992, Close=259.61998700000004, Volume=108330600, Adj Close=33.636249),
 Row(Date='2010-07-12', Open=258.53000299999997, High=261.84999799999997, Low=254.860012, Close=257.29000099999996, Volume=140719600, Adj Close=33.334377),
 Row(Date='2010-07-13', Open=256.319992, High=256.399994, Low=246.42999300000002, Close=251.79999500000002, Volume=297731000, Adj Close=32.623094),
 Row(Date='2010-07-14', Open=249.379993, High=255.800007, Low=249.000011, Close=252.73000299999998, Volume=203011900, Adj Close=32.743586),
 Row(Date='2010-07-15', Open=248.23000699999997, High=256.969994, Low=247.299999, Close=251.450001, Volume=206216500, Adj Close=32.577749),
 Row(Date='2010-07-16', Open=253.18, High=254.97000099999997, Low=248.410011, Close=249.900005, Volume=259964600, Adj Close=32.376932000000004),
 Row(Date='2010-07-19', Open=249.88000499999998, High=249.88000499999998, Low=239.60001, Close=245.58001299999998, Volume=256119500, Adj Close=31.817235999999998),
 Row(Date='2010-07-20', Open=242.900005, High=252.899994, Low=240.010006, Close=251.890011, Volume=268737700, Adj Close=32.634757),
 Row(Date='2010-07-21', Open=265.089993, High=265.149994, Low=253.999992, Close=254.23999799999999, Volume=296417800, Adj Close=32.93922),
 Row(Date='2010-07-22', Open=257.679996, High=259.999996, Low=255.31000899999998, Close=259.02, Volume=161329700, Adj Close=33.558515),
 Row(Date='2010-07-23', Open=257.089996, High=260.380005, Low=256.279991, Close=259.939995, Volume=133347200, Adj Close=33.677709),
 Row(Date='2010-07-26', Open=259.999996, High=260.09999799999997, Low=257.710011, Close=259.280006, Volume=105137900, Adj Close=33.592201),
 Row(Date='2010-07-27', Open=260.870003, High=264.799999, Low=260.300003, Close=264.08000899999996, Volume=146192900, Adj Close=34.214087),
 Row(Date='2010-07-28', Open=263.669987, High=265.990013, Low=260.249989, Close=260.959991, Volume=129996300, Adj Close=33.809859),
 Row(Date='2010-07-29', Open=260.70999900000004, High=262.64999, Low=256.099987, Close=258.10999300000003, Volume=160951700, Adj Close=33.440615),
 Row(Date='2010-07-30', Open=255.889996, High=259.699989, Low=254.900013, Close=257.25, Volume=112052500, Adj Close=33.329194),
 Row(Date='2010-08-02', Open=260.440006, High=262.589989, Low=259.61998700000004, Close=261.84999799999997, Volume=107013900, Adj Close=33.925168),
 Row(Date='2010-08-03', Open=261.01000600000003, High=263.259991, Low=259.42001, Close=261.93, Volume=104413400, Adj Close=33.935533),
 Row(Date='2010-08-04', Open=262.840008, High=264.279987, Low=260.30998999999997, Close=262.980011, Volume=105093800, Adj Close=34.071571999999996),
 Row(Date='2010-08-05', Open=261.72999599999997, High=263.17998900000003, Low=260.549995, Close=261.700008, Volume=72274300, Adj Close=33.905736),
 Row(Date='2010-08-06', Open=259.779991, High=261.48999, Low=257.630009, Close=260.090012, Volume=111224400, Adj Close=33.697145),
 Row(Date='2010-08-09', Open=261.48000299999995, High=262.15000499999996, Low=259.57, Close=261.749996, Volume=75782000, Adj Close=33.912212),
 Row(Date='2010-08-10', Open=259.850006, High=260.449993, Low=257.550007, Close=259.409996, Volume=112980000, Adj Close=33.609043),

In [84]:
df.filter(df["Low"]== 209.020004).collect()[0]

Row(Date='2010-01-14', Open=210.11000299999998, High=210.45999700000002, Low=209.020004, Close=209.43, Volume=108223500, Adj Close=27.133657)

In [85]:
df.filter(df["Low"]== 197.16).collect()  # In a lsit

[Row(Date='2010-01-22', Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)]

In [87]:
df.filter(df["Low"]== 197.16).collect()[0] # not in a list

Row(Date='2010-01-22', Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)

# Change to Dict

In [89]:
rows=df.filter(df["Low"]== 197.16).collect()[0] # not in a list
rows.asDict()

{'Date': '2010-01-22',
 'Open': 206.78000600000001,
 'High': 207.499996,
 'Low': 197.16,
 'Close': 197.75,
 'Volume': 220441900,
 'Adj Close': 25.620401}